/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_utils_test_libtess2jni_libtess2 */

#ifndef _Included_com_test_utils_test_libtess2jni_libtess2
#define _Included_com_test_utils_test_libtess2jni_libtess2
#ifdef __cplusplus
extern "C" {
#endif
#undef com_test_utils_test_libtess2jni_libtess2_TESS_UNDEF
#define com_test_utils_test_libtess2jni_libtess2_TESS_UNDEF -1L
/*
 * Class:     com_test_utils_test_libtess2jni_libtess2
 * Method:    _tessNewTess
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_test_utils_test_libtess2jni_libtess2__1tessNewTess
  (JNIEnv *, jclass);

/*
 * Class:     com_test_utils_test_libtess2jni_libtess2
 * Method:    _tessDeleteTess
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_test_utils_test_libtess2jni_libtess2__1tessDeleteTess
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_test_utils_test_libtess2jni_libtess2
 * Method:    tessAddContour
 * Signature: (Lcom/qunhe/diybe/utils/brep/libtess2jni/libtess2/TESStesselator;I[FIII)V
 */
JNIEXPORT void JNICALL Java_com_test_utils_test_libtess2jni_libtess2_tessAddContour
  (JNIEnv *, jclass, jobject, jint, jfloatArray, jint, jint, jint);

/*
 * Class:     com_test_utils_test_libtess2jni_libtess2
 * Method:    tessTesselate
 * Signature: (Lcom/qunhe/diybe/utils/brep/libtess2jni/libtess2/TESStesselator;IIII[F)I
 */
JNIEXPORT jint JNICALL Java_com_test_utils_test_libtess2jni_libtess2_tessTesselate
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jfloatArray);

/*
 * Class:     com_test_utils_test_libtess2jni_libtess2
 * Method:    tessGetVertexCount
 * Signature: (Lcom/qunhe/diybe/utils/brep/libtess2jni/libtess2/TESStesselator;)I
 */
JNIEXPORT jint JNICALL Java_com_test_utils_test_libtess2jni_libtess2_tessGetVertexCount
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_test_utils_test_libtess2jni_libtess2
 * Method:    tessGetVertices
 * Signature: (Lcom/qunhe/diybe/utils/brep/libtess2jni/libtess2/TESStesselator;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_test_utils_test_libtess2jni_libtess2_tessGetVertices
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_test_utils_test_libtess2jni_libtess2
 * Method:    tessGetVertexIndices
 * Signature: (Lcom/qunhe/diybe/utils/brep/libtess2jni/libtess2/TESStesselator;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_test_utils_test_libtess2jni_libtess2_tessGetVertexIndices
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_test_utils_test_libtess2jni_libtess2
 * Method:    tessGetElementCount
 * Signature: (Lcom/qunhe/diybe/utils/brep/libtess2jni/libtess2/TESStesselator;)I
 */
JNIEXPORT jint JNICALL Java_com_test_utils_test_libtess2jni_libtess2_tessGetElementCount
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_test_utils_test_libtess2jni_libtess2
 * Method:    tessGetElements
 * Signature: (Lcom/qunhe/diybe/utils/brep/libtess2jni/libtess2/TESStesselator;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_test_utils_test_libtess2jni_libtess2_tessGetElements
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
