/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qunhe_diybe_utils_brep_libtess2jni_libtess2_TessWindingRule */

#ifndef _Included_com_test_utils_test_libtess2jni_libtess2_TessWindingRule
#define _Included_com_test_utils_test_libtess2jni_libtess2_TessWindingRule
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
