/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_utils_test_libtess2jni_libtess2_TessElementType */

#ifndef _Included_com_test_utils_test_libtess2jni_libtess2_TessElementType
#define _Included_com_test_utils_test_libtess2jni_libtess2_TessElementType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
